### ISSUE TITLE
🐛 creating project doesnot work

### ISSUE THREAD

**Issue by prabincankod** [hqasmei/site-muse#3]
![Screen Shot 2023-09-12 at 11 15 07 PM](https://github.com/hqasmei/site-muse/assets/42871240/d41300d5-b96c-4d72-a148-4bc3e3a168a3)

**Comment by hqasmei** [comment]
Thanks, on it. Was working on adding a feature and pushed without fully testing it.

**Comment by prabincankod** [comment]
> Thanks, on it. Was working on adding a feature and pushed without fully testing it.
 Your vercel builds are failing but it is working in the local.

**Comment by prabincankod** [comment]
either you could take 2 screenshots (for desktop and mobile) and store 'em in the uploadThing and then finally store their key and url in the database in two separate two fields or ask the user for size of screenshot when creating the link and store them accordingly.

**Comment by hqasmei** [comment]
Oh I know. It's because I changed my env variables and forgot to update it in Vercel. Just did it now so should be working. Thanks for that.
