### ISSUE TITLE
create link working in dev, not in prod

### ISSUE THREAD

**Issue by hqasmei** [hqasmei/site-muse#4]

**Comment by prabincankod** [comment]
lemme check!!

**Comment by prabincankod** [comment]
i was about to suggest to suggest the same thing, using timeout in axios request

**Comment by prabincankod** [comment]
@hqasmei which api screenshot api service are you using ?

**Comment by hqasmei** [comment]
using https://3.screeenly.com/.

One issue was the execution time, was over 10s. so i upgraded to pro in vercel. It's still failing but for another reason now, trying to figure out where. its not processing the promise of where im uploading using upload thing.

**Comment by prabincankod** [comment]
i want to fix this issue.

**Comment by hqasmei** [comment]
Ah I think I know what the issue is. So uploadthing needs node 18.17. Vercel uses 18.12. So the upload can't complete. 
Locally my machine uses 18.17 so that is why it completes. I dont believe vercel lets you change the node version. Might have to use cloudinary instead of uplaodthing for now.

**Comment by prabincankod** [comment]
@hqasmei creating link on desktop type works . https://site-muse.vercel.app/

**Comment by hqasmei** [comment]
![Screenshot 2023-09-12 at 3 36 19 PM](https://github.com/hqasmei/site-muse/assets/39573679/04c118f8-909d-42cc-9535-f653ea59f6c4)

**Comment by hqasmei** [comment]
i keep getting this error, even with the link you shared. It was working before which is weird i dont know where this error is coming from.

**Comment by prabincankod** [comment]
i guess that is coming from create link modal

**Comment by prabincankod** [comment]
@hqasmei desktop works now.

https://github.com/hqasmei/site-muse/assets/42871240/15ec7b37-cd31-4b7c-a21f-173bc8cc615e

**Comment by prabincankod** [comment]
Refs #5 
i am close to resolving the whole issue

**Comment by hqasmei** [comment]
Even after merging I still get the error. What did you do to get the above to work?

**Comment by prabincankod** [comment]
lets chat over this on discord.

**Comment by hqasmei** [comment]
The issue was the env in vercel
